// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyEkwxpRVPICYZH7jlOs-Zr-qhWoh0n7E',
    appId: '1:1060054235630:web:6fc659fbdd31d8966cf6ff',
    messagingSenderId: '1060054235630',
    projectId: 'cmsc23-kmalcala',
    authDomain: 'cmsc23-kmalcala.firebaseapp.com',
    storageBucket: 'cmsc23-kmalcala.appspot.com',
    measurementId: 'G-C7D8JX913R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDx6w_mJ2XGnAZ_VJYQ6u_pxuvu3d2JRdo',
    appId: '1:1060054235630:android:20ff7f820d1ae91e6cf6ff',
    messagingSenderId: '1060054235630',
    projectId: 'cmsc23-kmalcala',
    storageBucket: 'cmsc23-kmalcala.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUuKPkmGgG8qF7RVH38GPWvjRV4AVpgmQ',
    appId: '1:1060054235630:ios:7ad0a53bbdb754b46cf6ff',
    messagingSenderId: '1060054235630',
    projectId: 'cmsc23-kmalcala',
    storageBucket: 'cmsc23-kmalcala.appspot.com',
    iosClientId: '1060054235630-or9qhguood7ntb9fn3cutr4laadsf78c.apps.googleusercontent.com',
    iosBundleId: 'com.example.week7NetworkingDiscussion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUuKPkmGgG8qF7RVH38GPWvjRV4AVpgmQ',
    appId: '1:1060054235630:ios:7ad0a53bbdb754b46cf6ff',
    messagingSenderId: '1060054235630',
    projectId: 'cmsc23-kmalcala',
    storageBucket: 'cmsc23-kmalcala.appspot.com',
    iosClientId: '1060054235630-or9qhguood7ntb9fn3cutr4laadsf78c.apps.googleusercontent.com',
    iosBundleId: 'com.example.week7NetworkingDiscussion',
  );
}
